<a href="https://colab.research.google.com/github/19692yq/BAN-Lab-assignment-2-Yinghui-Qiang/blob/main/Project_2_Mean_Variiance_STD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [320]:
import numpy as np
import statistics


# step 1. Get 9 digits

**method 1**

In [321]:
def calculate(list):
  if len(list)!=9:
    raise ValueError("List must contain nine numbers.")

  list=np.array(list).reshape(3,3)

  calculations={}

  calculations['mean']=[list.mean(axis=0).tolist(), list.mean(axis=1).tolist(), np.mean(list).tolist()]
  calculations['variance']=[list.var(axis=0).tolist(), list.var(axis=1).tolist(), np.var(list).tolist()]
  calculations['standard deviation']=[list.std(axis=0).tolist(), list.std(axis=1).tolist, np.std(list).tolist()]
  calculations ['max']=[list.max(axis=0).tolist(), list.max(axis=1).tolist, np.max(list).tolist()]
  calculations['min']=[list.min(axis=0).tolist(), list.min(axis=1).tolist, np.min(list).tolist()]
  calculations['sum']=[list.sum(axis=0).tolist(), list.sum(axis=1).tolist, np.sum(list).tolist()]


  return calculations


In [322]:
#ANS
print(calculate([0,1,2,3,4,5,6,7,8]))

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], <built-in method tolist of numpy.ndarray object at 0x7bb96d8f76f0>, 2.581988897471611], 'max': [[6, 7, 8], <built-in method tolist of numpy.ndarray object at 0x7bb96d8f7b70>, 8], 'min': [[0, 1, 2], <built-in method tolist of numpy.ndarray object at 0x7bb96d8f7ab0>, 0], 'sum': [[9, 12, 15], <built-in method tolist of numpy.ndarray object at 0x7bb96d584bd0>, 36]}


In [323]:
print(list)

<class 'list'>


**method2**

In [324]:
import statistics

In [325]:
a=np.array([0,1,2,3,4,5,6,7,8])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [326]:
aa=a.reshape(3,3)

In [327]:
aa

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [328]:
mean_c=np.mean(aa,axis=0).tolist()
mean_c

[3.0, 4.0, 5.0]

In [329]:
mean_r=np.mean(aa, axis=1).tolist()
mean_r

[1.0, 4.0, 7.0]

In [330]:
mean_t=np.mean(aa).tolist()
mean_t

4.0

In [331]:
var_c=np.var(aa,axis=0).tolist()
var_c

[6.0, 6.0, 6.0]

In [332]:
var_r=np.var(aa,axis=1).tolist()
var_r

[0.6666666666666666, 0.6666666666666666, 0.6666666666666666]

In [333]:
var_t=np.var(aa).tolist()
var_t

6.666666666666667

In [334]:
max_c=np.max(aa,axis=0).tolist()
max_c

[6, 7, 8]

In [335]:
std_c=np.std(aa,axis=0).tolist()
std_c

[2.449489742783178, 2.449489742783178, 2.449489742783178]

In [336]:
std_r=np.std(aa,axis=1).tolist()
std_r

[0.816496580927726, 0.816496580927726, 0.816496580927726]

In [337]:
std_t=np.std(aa).tolist()
std_t

2.581988897471611

In [338]:
max_r=np.max(aa,axis=1).tolist()
max_r

[2, 5, 8]

In [339]:
max_c=np.max(aa,axis=0).tolist()

In [340]:
max_t=np.max(aa).tolist()
max_t

8

In [341]:
min_c=np.min(aa,axis=0).tolist()
min_c

[0, 1, 2]

In [342]:
min_r=np.min(aa,axis=1).tolist()
min_r

[0, 3, 6]

In [343]:
min_t=np.min(aa).tolist()
min_t

0

In [344]:
sum_r=np.sum(aa,axis=1).tolist()
sum_r

[3, 12, 21]

In [345]:
sum_c=np.sum(aa,axis=0).tolist()
sum_c

[9, 12, 15]

In [346]:
sum_t=np.sum(aa).tolist()
sum_t

36

In [347]:
#ANS
a1={'mean':[mean_c,mean_r,mean_t],"var":[var_c,var_r,var_t],"std":[std_c,std_r,std_t],"max":[max_c,max_r,max_t],"min":[min_c,min_r,min_t],"sum":[sum_c,sum_r,sum_t]}
a1

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'var': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'std': [[2.449489742783178, 2.449489742783178, 2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}

**Method 3**

In [367]:
def calculate(list):
  if len(list)!=9:
    raise ValueError("List must contain nine numbers.")

  list=np.array(list).reshape(3,3)


  mean=[list.mean(axis=0).tolist(), list.mean(axis=1).tolist(), np.mean(list).tolist()]
  variance=[list.var(axis=0).tolist(), list.var(axis=1).tolist(), np.var(list).tolist()]
  standard_deviation=[list.std(axis=0).tolist(), list.std(axis=1).tolist, np.std(list).tolist()]
  max=[list.max(axis=0).tolist(), list.max(axis=1).tolist, np.max(list).tolist()]
  min=[list.min(axis=0).tolist(), list.min(axis=1).tolist, np.min(list).tolist()]
  sum=[list.sum(axis=0).tolist(), list.sum(axis=1).tolist, np.sum(list).tolist()]


  return {
      "mean": mean,
      "variance": variance,
      "standard_deviation": standard_deviation,
      "max": max,
      "min": min,
      "sum":sum

  }

  return calculation

In [372]:
print(calculate([11,12,33,14,15,16,17,18,19]))

{'mean': [[14.0, 15.0, 22.666666666666668], [18.666666666666668, 15.0, 18.0], 17.22222222222222], 'variance': [[6.0, 6.0, 54.88888888888889], [102.88888888888887, 0.6666666666666666, 0.6666666666666666], 37.283950617283956], 'standard_deviation': [[2.449489742783178, 2.449489742783178, 7.408703590297623], <built-in method tolist of numpy.ndarray object at 0x7bb96d67a790>, 6.106058517348483], 'max': [[17, 18, 33], <built-in method tolist of numpy.ndarray object at 0x7bb96d678d50>, 33], 'min': [[11, 12, 16], <built-in method tolist of numpy.ndarray object at 0x7bb96d67b2d0>, 11], 'sum': [[42, 45, 68], <built-in method tolist of numpy.ndarray object at 0x7bb96d67a610>, 155]}


**Other**

In [350]:
type(a1)

dict

In [351]:
a1=np.arange(10,19)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [352]:
np.sum(a1)

126

In [353]:
def calculate(list):
  list=np.array(list)

  return{mean_c,mean_r,mean_t}


In [354]:
print(list)

<class 'list'>


In [355]:
def calculate(mean, var,std):
  print("hi")
calculate

<function __main__.calculate(mean, var, std)>